from flask import Blueprint, request, jsonify
from app.agents.urban_agent import UrbanAgent

# Create a Blueprint for the urban routes
urban_bp = Blueprint('urban', __name__)

# Initialize the agent
agent = UrbanAgent()

@urban_bp.route("/api/ask", methods=["POST"])
def ask():
    """
    Handle a POST request to the /api/ask endpoint.
    This endpoint processes a question sent in the request body and returns a response
    generated by the UrbanAgent.
    """
    try:
        # Get the question from the request JSON
        data = request.json
        question = data.get("question")  # Get the 'question' from the request

        if not question or len(question.strip()) == 0:
            return jsonify({"error": "Question cannot be empty"}), 400  # HTTP 400 Bad Request

        # Use the UrbanAgent to process the question
        response = agent.run(question)

        # Return the response in JSON format
        return jsonify({"response": response}), 200  # HTTP 200 OK

    except Exception as e:
        return jsonify({"error": str(e)}), 500  # HTTP 500 Internal Server Error

@urban_bp.route("/", methods=["GET"])
def health_check():
    """Health check endpoint"""
    return jsonify({"status": "healthy"}), 200



